### ISSUE TITLE
login redirect to checkout

### ISSUE THREAD

**Issue by homepods** [codingforentrepreneurs/ecommerce-2#1]
Why isn't the login re-directing to checkout page when login required is required? the login_required gets the next link as in`/accounts/login/?next=/checkout/` but it doesn't redirect to the same link after login.
Is there a bug or you don't want us to know something??

**Comment by codingforentrepreneurs** [comment]
This is likely an bug with Django Registration Redux. You can consider using Django All Auth or Simple Custom Auth (both you can learn about on http://joincfe.com/project/)
